"""Static recompiler driver: DOL + symbols -> C++ translation units.

Usage: python recomp.py [--out DIR] [--dol PATH] [--hle hle_list.txt] [--tu-insns N]
Generated code is not committed (see .gitignore); rerun after changing the emitter.
"""
import argparse
import hashlib
import re
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from dol import Dol
from symbols import SymbolMap
from analyze import analyze_all
from emit import Emitter

ROOT = Path(__file__).resolve().parents[2]


MACRO_LIKE = {"errno", "stdin", "stdout", "stderr", "NULL", "EOF", "min", "max", "TRUE", "FALSE", "BOOL",
              "assert", "offsetof", "alloca", "environ", "abs", "unix", "linux", "far", "near", "pascal",
              "interface", "small", "hyper"}


def c_ident(name):
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not s or s[0].isdigit():
        s = "_" + s
    # CRT/Windows macros: _errno, errno, stdin... Prefix so the header never expands a macro.
    if s in MACRO_LIKE or re.match(r"^_[a-z]", s):
        s = "s" + s if s.startswith("_") else "s_" + s
    return s


def write_if_changed(path, text):
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "port/generated"))
    ap.add_argument("--dol", default=str(ROOT / "melee/orig/GALE01/sys/main.dol"))
    ap.add_argument("--symbols", default=str(ROOT / "melee/config/GALE01/symbols.txt"))
    ap.add_argument("--hle", default=str(ROOT / "port/recomp/hle_list.txt"))
    ap.add_argument("--tu-insns", type=int, default=7000)
    args = ap.parse_args()

    t0 = time.time()
    dol = Dol(args.dol)
    symbols = SymbolMap(args.symbols)
    infos, extra = analyze_all(dol, symbols)
    hle = set()
    for line in open(args.hle, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if line:
            hle.add(line)
    missing = sorted(n for n in hle if n not in symbols.by_name)
    if missing:
        print("warning: HLE names not in symbol map:", ", ".join(missing))
    hle_funcs = {n for n in hle if n in symbols.by_name}

    func_names = {addr: "f_%08X" % addr for addr in infos}
    emitter = Emitter(dol, symbols, infos, hle_funcs, func_names)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    changed = 0

    # Prototypes for every function.
    text = ["// Generated by port/recomp/recomp.py. Do not edit.\n#pragma once\n#include \"ppc.h\"\n",
            "#include \"hle_decls.h\"\nnamespace guest {\n"]
    for addr in sorted(infos):
        text.append("void %s(ppc::Context&, uint8_t*);\n" % func_names[addr])
    text.append("struct FnEntry { uint32_t addr; ppc::Fn fn; };\n")
    text.append("extern const FnEntry fn_table[];\nextern const size_t fn_table_count;\n}\n")
    changed += write_if_changed(out / "functions.h", "".join(text))

    # HLE declarations.
    text = ["// Generated. HLE overrides referenced by generated code.\n#pragma once\n#include \"ppc.h\"\nnamespace hle {\n"]
    for name in sorted(hle_funcs):
        text.append("void %s(ppc::Context& c, uint8_t* m);\n" % name)
    text.append("}\n")
    changed += write_if_changed(out / "hle_decls.h", "".join(text))

    # Guest symbol addresses for host code (functions and objects).
    text = ["// Generated guest symbol addresses.\n#pragma once\n#include <cstdint>\nnamespace gs {\n"]
    used = set()
    for addr, name in sorted(symbols.names.items()):
        ident = c_ident(name)
        if ident in used:
            ident = "%s_%08X" % (ident, addr)
        used.add(ident)
        text.append("constexpr uint32_t %s = 0x%08Xu;\n" % (ident, addr))
    text.append("}\n")
    changed += write_if_changed(out / "guest_symbols.h", "".join(text))

    # Translation units.
    ordered = sorted(infos)
    tu_index = 0
    count = 0
    chunk = []
    written = []

    def flush():
        nonlocal tu_index, chunk, count, changed
        if not chunk:
            return
        path = out / ("guest_%03d.cpp" % tu_index)
        body = ("// Generated by port/recomp/recomp.py from main.dol. Do not edit.\n"
                "#include \"functions.h\"\n#include <intrin.h>\nnamespace guest {\n" + "".join(chunk) + "}\n")
        changed += write_if_changed(path, body)
        written.append(path)
        tu_index += 1
        chunk = []
        count = 0

    for addr in ordered:
        info = infos[addr]
        chunk.append(emitter.emit_function(info))
        chunk.append("\n")
        count += len(info.insns)
        if count >= args.tu_insns:
            flush()
    flush()
    for old in out.glob("guest_*.cpp"):
        if old not in written and old.name != "guest_table.cpp":
            old.unlink()

    text = ["#include \"functions.h\"\nnamespace guest {\nconst FnEntry fn_table[] = {\n"]
    for addr in ordered:
        text.append("  {0x%08Xu, &%s},\n" % (addr, func_names[addr]))
    text.append("};\nconst size_t fn_table_count = sizeof(fn_table) / sizeof(fn_table[0]);\n}\n")
    changed += write_if_changed(out / "guest_table.cpp", "".join(text))

    text = ["set(GUEST_SOURCES\n"]
    for p in written:
        text.append("  \"${CMAKE_CURRENT_LIST_DIR}/%s\"\n" % p.name)
    text.append("  \"${CMAKE_CURRENT_LIST_DIR}/guest_table.cpp\"\n)\n")
    changed += write_if_changed(out / "guest_sources.cmake", "".join(text))

    # Names for diagnostics.
    text = ["#include <cstdint>\n#include <cstddef>\nnamespace guest {\nstruct NameEntry { uint32_t addr; const char* name; };\n",
            "extern const NameEntry name_table[];\nextern const size_t name_table_count;\n",
            "const NameEntry name_table[] = {\n"]
    for func in symbols.functions:
        text.append("  {0x%08Xu, \"%s\"},\n" % (func.addr, func.name.replace("\\", "\\\\").replace('"', '\\"')))
    text.append("};\nconst size_t name_table_count = sizeof(name_table) / sizeof(name_table[0]);\n}\n")
    changed += write_if_changed(out / "function_names.cpp", "".join(text))

    digest = hashlib.sha1(dol.ram).hexdigest()[:12]
    print("generated %d TUs, %d functions, %d HLE overrides, %d files changed, image %s, %.1fs" % (
        len(written), len(infos), len(hle_funcs), changed, digest, time.time() - t0))


if __name__ == "__main__":
    main()
