"""Import GD's compiled font assets and exact glyph metrics without rerasterizing.

Inputs are separately reviewed upstream checkouts; see ui_sources/gd_melee/ORIGIN.md.
"""
import argparse
import importlib.util
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('workspace', type=Path)
    ap.add_argument('runtime', type=Path)
    args = ap.parse_args()
    dest = ROOT / 'port/runtime/gx/ui_sources/gd_melee'
    assets = dest / 'assets/kit'
    assets.mkdir(parents=True, exist_ok=True)
    spec = importlib.util.spec_from_file_location('png2gx', args.runtime / 'pc/tools/png2gx.py')
    decoder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(decoder)
    source = args.workspace / '_build/ui'
    manifest = json.loads((source / 'font_manifest.json').read_text())
    shutil.copy2(source / 'font_manifest.json', assets)
    for name in ('kit', 'chrome_layout', 'list_layout', 'widgets_layout', 'kit_motion'):
        shutil.copy2(args.workspace / 'menu/out_kit' / (name + '.json'), assets)
    shutil.copy2(args.workspace / 'menu/SourceSans3/LICENSE.md', assets / 'SourceSans3-OFL.md')
    for font in ('SourceSans3-Bold.otf', 'SourceSans3-Black.otf'):
        shutil.copy2(args.workspace / 'menu/SourceSans3' / font, assets)
    text = ['// Generated by tools/import_gd_kit.py from the upstream font manifest.',
            '// Font artwork and metrics: SIL OFL 1.1; see assets/kit/SourceSans3-OFL.md.',
            '#pragma once', 'namespace gd_font_data {',
            'struct Glyph { unsigned cp; float advance, x, y, w, h, u0, v0, u1, v1; };',
            'struct Kern { unsigned a, b; float value; };',
            'struct Role { const char* name; const char* page; const Glyph* glyphs; int glyph_count; const Kern* kern; int kern_count; bool caps; };']
    def f(v):
        return ('%.6f' % v).rstrip('0').rstrip('.') + ('.0f' if float(v).is_integer() else 'f')
    names = ('caption', 'body', 'row', 'label', 'title', 'heading', 'hero', 'display')
    for asset in ('ico_options', 'glyph_a', 'glyph_b', 'glyph_dpad'):
        decoder.decode_gxtex(str(source / (asset + '.gxtex'))).save(assets / (asset + '.png'))
    for name in names:
        role = manifest['roles'][name]
        pages = role['pages']['latin']
        assert len(pages) == 1
        decoder.decode_gxtex(str(source / (pages[0] + '.gxtex'))).save(assets / (pages[0] + '.png'))
        text.append('static constexpr Glyph ' + name + '_glyphs[] = {')
        for ch, g in sorted(role['glyphs'].items()):
            assert len(ch) == 1
            values = [g['advance']] + g.get('offset', [0, 0]) + g.get('size', [0, 0]) + g.get('uv', [0, 0, 0, 0])
            text.append('{' + str(ord(ch)) + ',' + ','.join(f(v) for v in values) + '},')
        text.append('};\nstatic constexpr Kern ' + name + '_kern[] = {')
        for pair, value in sorted(role.get('kerning', {}).items()):
            text.append('{%d,%d,%s},' % (ord(pair[0]), ord(pair[1]), f(value)))
        text.append('};')
    text.append('static constexpr Role roles[] = {')
    for name in names:
        r = manifest['roles'][name]
        text.append('{"%s","kit/%s.png",%s_glyphs,%d,%s_kern,%d,%s},' %
                    (name, r['pages']['latin'][0], name, len(r['glyphs']), name, len(r.get('kerning', {})),
                     'true' if r['charset'] == 'caps' else 'false'))
    text.append('};\n} // namespace gd_font_data\n')
    (dest / 'font_metrics.h').write_text('\n'.join(text), encoding='utf-8')
    print('Imported %d exact font atlases and metrics into %s' % (len(names), assets))


if __name__ == '__main__':
    main()
